# Generated by Django 6.0.4 on 2026-04-08 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Nome da categoria", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ItemCardapio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Nome do item", max_length=200)),
                ("descricao", models.TextField(help_text="Descrição do item")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço do item em reais",
                        max_digits=8,
                    ),
                ),
                (
                    "disponivel",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o item está disponível para pedido",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Categoria à qual este item pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Cardápio",
                "verbose_name_plural": "Itens do Cardápio",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que o pedido foi realizado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("em_preparo", "Em Preparo"),
                            ("pronto", "Pronto"),
                            ("entregue", "Entregue"),
                        ],
                        default="recebido",
                        help_text="Status atual do pedido",
                        max_length=20,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações adicionais do cliente sobre o pedido",
                        null=True,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que realizou o pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantidade do item no pedido"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Item do cardápio selecionado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.itemcardapio",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        help_text="Pedido ao qual este item pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="cardapio.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gerente", "Gerente"),
                            ("atendente", "Atendente"),
                            ("cliente", "Cliente"),
                        ],
                        default="cliente",
                        help_text="Tipo de acesso do usuário no sistema",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        help_text="Usuário do Django associado a este perfil",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis",
            },
        ),
    ]
