# Generated by Django 6.0.4 on 2026-04-15 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                    ("pix", "PIX"),
                ],
                help_text="Forma de pagamento escolhida pelo cliente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                help_text="Estado atual do pagamento",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CartaoSalvo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        help_text="Ex: Nubank, Visa final 1234", max_length=50
                    ),
                ),
                ("nome_titular", models.CharField(max_length=200)),
                (
                    "numero_mascarado",
                    models.CharField(
                        help_text="Ex: **** **** **** 1234", max_length=19
                    ),
                ),
                (
                    "bandeira",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("elo", "Elo"),
                            ("amex", "American Express"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("credito", "Crédito"), ("debito", "Débito")],
                        max_length=10,
                    ),
                ),
                ("validade", models.CharField(help_text="MM/AAAA", max_length=7)),
                (
                    "cvv",
                    models.CharField(
                        help_text="Código de segurança do cartão", max_length=4
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Cliente dono do cartão",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão Salvo",
                "verbose_name_plural": "Cartões Salvos",
                "ordering": ["apelido"],
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="cartao_utilizado",
            field=models.ForeignKey(
                blank=True,
                help_text="Cartão salvo usado neste pedido (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cardapio.cartaosalvo",
            ),
        ),
    ]
