# Generated by Django 6.0.4 on 2026-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0002_pedido_forma_pagamento_pedido_status_pagamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                ],
                help_text="Forma de pagamento escolhida pelo cliente",
                max_length=20,
            ),
        ),
    ]
